# Generated by Django 5.1.1 on 2024-10-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_original', models.CharField(default='nun', max_length=255)),
                ('origem', models.CharField(default='nun', max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=22)),
                ('endereco', models.CharField(max_length=255)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('numero_venda_original', models.CharField(default='nun', max_length=255)),
                ('origem', models.CharField(default='nun', max_length=50)),
                ('canal_venda', models.CharField(max_length=255)),
                ('data_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_original', models.CharField(default='nun', max_length=255)),
                ('origem', models.CharField(default='nun', max_length=50)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id_item_venda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='coremodels.clientes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='coremodels.produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='coremodels.vendas')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='coremodels.vendedores')),
            ],
        ),
    ]
