# Generated by Django 5.1.1 on 2024-10-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0002_alter_clientes_cep_alter_clientes_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='canal_venda',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientes',
            unique_together={('id_original', 'origem')},
        ),
        migrations.AlterUniqueTogether(
            name='vendas',
            unique_together={('numero_venda_original', 'origem')},
        ),
    ]
