# Generated by Django 5.1.1 on 2024-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0003_alter_vendas_canal_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
