# Generated by Django 5.1.1 on 2024-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0004_alter_vendas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='origem',
            field=models.CharField(default='nun', max_length=50),
        ),
    ]
