# Generated by Django 5.1.1 on 2024-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0005_itemvenda_origem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('venda', 'produto')},
        ),
    ]
