# Generated by Django 5.1.1 on 2024-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0006_alter_itemvenda_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
