# Generated by Django 5.1.1 on 2024-10-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0007_alter_produtos_custo_alter_produtos_estoque_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('venda', 'produto', 'origem')},
        ),
    ]
