# Generated by Django 5.1.1 on 2024-10-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0008_alter_itemvenda_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_cliente', to='coremodels.clientes'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='coremodels.produtos'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_vendedor', to='coremodels.vendedores'),
        ),
    ]
