# Generated by Django 5.1.3 on 2024-11-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0011_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='situacao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
