# Generated by Django 5.1.3 on 2024-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0012_vendas_situacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientes',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vendas',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('venda', 'produto')},
        ),
        migrations.RemoveField(
            model_name='vendedores',
            name='id_original',
        ),
        migrations.RemoveField(
            model_name='vendedores',
            name='origem',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='id_original',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='numero_venda_original',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='origem',
        ),
    ]
