# Generated by Django 5.1.3 on 2024-11-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0013_alter_clientes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
