# Generated by Django 5.1.3 on 2024-11-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0014_alter_clientes_id_alter_vendas_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['descricao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='estoque',
            new_name='estoque_disponivel',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='preco_unitario',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='codigo',
            new_name='sku',
        ),
        migrations.AddField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='codigo_regime_tributario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='contribuinte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='clientes',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='unidade',
            field=models.CharField(blank=True, default='un', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=10),
        ),
    ]
