# Generated by Django 5.1.3 on 2024-11-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0016_clientes_rota_alter_clientes_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='loja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='loja',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
