# Generated by Django 5.1.3 on 2024-11-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0019_alter_clientes_celular_alter_clientes_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=100),
        ),
    ]
