# Generated by Django 5.1.3 on 2024-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0020_alter_clientes_situacao_alter_clientes_tipo_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='numero',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
