# Generated by Django 5.1.3 on 2024-12-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0022_itemvenda_bairro_entrega_itemvenda_cep_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_vendedor', to='coremodels.vendedores'),
        ),
    ]
