# Generated by Django 5.1.3 on 2024-12-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0023_alter_itemvenda_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade_produto',
            field=models.FloatField(),
        ),
    ]
