# Generated by Django 5.1.3 on 2024-12-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0024_alter_itemvenda_quantidade_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_rota', models.CharField(max_length=255)),
                ('dia_semana', models.IntegerField()),
                ('Numero_rota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CidadesRotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=255)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades_rota', to='coremodels.rotas')),
            ],
        ),
    ]
