# Generated by Django 5.1.3 on 2024-12-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coremodels', '0025_rotas_cidadesrotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_rota', to='coremodels.rotas'),
        ),
    ]
